Update generate.yml

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -1,4 +1,3 @@
-
 name: Генерация артефактов из Protobuf
 
 on:
@@ -40,10 +39,10 @@ jobs:
       run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
 
     - name: Генерация Go-кода
-      run: protoc --go_out=. --go-grpc_out=. auth.proto
+      run: protoc --go_out=./proto --go-grpc_out=./proto ./auth.proto
      
     - name: Проверка наличия сгенерированного файла
-      run: ls -la
+      run: ls -la ./proto
 
     - name: Checkout Go module repository
       uses: actions/checkout@v2
@@ -54,12 +53,12 @@ jobs:
 
     - name: Copy generated files
       run: |
-       if [ -f proto/auth.pb.go ]; then
-       cp proto/auth.pb.go go-proto-module/
-       else
-       echo "File proto/auth.pb.go not found!"
-       exit 1
-       fi
+        if [ -f ./proto/auth.pb.go ]; then
+          cp ./proto/auth.pb.go go-proto-module/
+        else
+          echo "File ./proto/auth.pb.go not found!"
+          exit 1
+        fi
 
     - name: Commit and push changes
       run: |
@@ -67,12 +66,13 @@ jobs:
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout -B update-protobuf-files  # Создаем или переключаемся на ветку
-        git fetch origin update-protobuf-files  # Получаем последние изменения из удаленной ветки
-        git reset --hard origin/update-protobuf-files  # Сбрасываем изменения к последнему коммиту ветки
+        git fetch origin update-protobuf-files || true  # Получаем последние изменения из удаленной ветки
+        git reset --hard origin/update-protobuf-files || true  # Сбрасываем изменения к последнему коммиту ветки
         rm -f auth.pb.go  # Удаляем существующий файл, если он есть
         cp ../proto/auth.pb.go .  # Копируем новый файл
         git add auth.pb.go
-        git commit --allow-empty -m "Update generated protobuf files"
+        git status  # Проверяем статус
+        git commit -m "Update generated protobuf files" || true  # Делаем коммит, если есть изменения
         git push origin update-protobuf-files
 
     - name: Create Pull Request
